name: Node.js CI

on:
  push:
    branches: [ github_actions ]
  # pull_request:
  #   branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Get repositary code
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          # node-version: ${{ matrix.node-version }}
          node-version: 20.x
      - name: Install modules
        run: npm ci
      # - run: npm run build --if-present
      - name: Run test
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build docker image
        uses: appleboy/ssh-action@v0.1.10
        env:
          BRANCH: ${GITHUB_REF_NAME}
        with:
          host: ${{ secrets.ZEUS_HOST }}
          username: ${{ secrets.ZEUS_USER }}
          key: ${{ secrets.ZEUS_SSH_PRIVATE_KEY }}
          port: 22
          envs: BRANCH
          script: |
            echo "dddd = $BRANCH"
            cd `mktemp -d`
            git clone --branch $BRANCH --single-branch https://github.com/AazAlena/pet_project.git .
            docker build -t pet_project:$BRANCH .